### ISSUE TITLE
Axis-System rotation config

### ISSUE THREAD

**Issue by Flo2410** [ros2/teleop_twist_keyboard#32]
I have a robot which has a 90° rotated coordinate system (y-axis is forward/back and x-axis is sideways). 

Therefore, it would be nice to be able to rotate the system for the teleop as well.

**Comment by clalancette** [comment]
> I have a robot which has a 90° rotated coordinate system (y-axis is forward/back and x-axis is sideways).

Honestly, I'm not sure that this is a good feature.

The problem is that most of ROS assumes software conforms to https://www.ros.org/reps/rep-0103.html .  So while we could add in a configuration here, the rest of ROS probably wouldn't work properly.

My best suggestion here is to write a node that transforms your coordinate frame to a ROS-compatible one.  That way it will work for this package, and all other ROS packages.
